### PR TITLE
Update to latest chado dump

### PR DESCRIPTION
**Pull request by abretaud**
Let's try to update this image with a more recent chado build
https://github.com/erasche/chado-schema-builder/releases/tag/1.31-jenkins21

### CODE REVIEW

**Comment by hexylena** [comment]
Looks good. Ugh we're going to hit a numbering conflict sooner or later. Should we delete old ones? Or put `-eu` in the tag or something?

**Comment by abretaud** [comment]
Oh... I think we can delete most of the old releases. Maybe keeping the 110 one a little longer as I still use it a lot, but I think we could rename it in github?

**Comment by hexylena** [comment]
We don't really *need* to delete any old releases and I'd feel a bit bad if someone is using them. But then again I'm not sure historical versions are truly useful. Ah well, we've got... 88 - 21 ... so 67 months until we have to make that decision? (Assuming that we don't create any more duplicates)

**Comment by abretaud** [comment]
Yes, maybe waiting is the best solution for now :D

**Pull request merged**
